#!/bin/bash

SCRIPT_TARGET="https://raw.githubusercontent.com/nuxeo-sandbox/nuxeo-tools-cloudformation/master/scripts/@@Nuxeo_single@@"
apt-get update && apt-get install -q -y curl && curl -O /install_script -sSL ${SCRIPT_TARGET}
/bin/bash /install_script