#!/bin/bash

add-apt-repository -y ppa:alestic/ppa && apt-get update && apt-get install -q -y runurl
runurl https://raw.githubusercontent.com/nuxeo-sandbox/nuxeo-tools-cloudformation/master/scripts/Nuxeo_single

